name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage                            

      - name: Install spotipy
        run: sudo pip3 install spotipy

      - name: Install requests
       run: sudo pip3 install requests

      - name: Install pandas
       run: sudo pip3 install pandas

      - name: Install sqlalchemy
       run: sudo pip3 install sqlalchemy

      - name: Test with unittest
        run: python3 -m unittest spotTest.py
       
       #add your code below this line
     
     - name: Check code coverage                        #new from here down
        run: |
          python3 -m coverage run -m unittest spotTest.py
          python3 -m coverage report
          python3 -m coverage html
          
      - name: Archive code coverage HTML report
        uses: actions/upload-artifact@v2
        with:
           name: code-coverage-report
           path: htmlcov